force-app/main/default/objects/Asset/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote line that generated this asset.</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Modified_Root_Asset__c.field-meta.xml
<CustomField>
    <fullName>Modified_Root_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modified Root Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Order Products (Modified By)</relationshipLabel>
    <relationshipName>ModifiedBy_OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__BundleRoot__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__BundleRoot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The root bundle parent Order Product of components. This component will be deleted if its bundle root is deleted.</description>
    <inlineHelpText>An internally used field that points to the root of its bundle parent.</inlineHelpText>
    <label>Bundle Root</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products (Bundle Root)</relationshipLabel>
    <relationshipName>BundleChildren</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line where this order product is created from.</description>
    <inlineHelpText>The quote line where this order product is created from.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required By</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__ShippingAccount__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ShippingAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>ShippingAccountOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RequiredBy__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RequiredBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
    <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
    <label>Required By</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__UpgradedAsset__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__UpgradedAsset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asset being upgraded by this quote line. Only populated if this quote line represents an upgrade.</description>
    <inlineHelpText>Asset being upgraded by this quote line. When the quote is contracted this asset will have its Usage End Date populated to indicate it&apos;s retired.</inlineHelpText>
    <label>Upgraded Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quote Lines (Upgrade)</relationshipLabel>
    <relationshipName>UpgradeLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpsertAssets.cls
public with sharing class UpsertAssets {
    
    private static List<String> orderItemFields() {
        return new List<String>{

        };
    }
    public static void upsert(Id orderId) {
        List<OrderItem> ois = PWUtils.selectStar(...);
        for (OrderItem oi : ois) {
            if(!isRootOrderItem(oi)) {
                continue;
            }
            String rootAssetId = getRootAssetId(oi);
            if(rootAssetId == null) {
                rootAssetId = 'TEMP:' + oi.Id;
            }
            rootAssetIds.add(rootAssetId);
        }
        for (String rootAssetId : rootAssetIds) {
            NestedObject bom;
            if(rootAssetId.startsWith('TEMP:')) {
                bom = getBOMForOrderItem(rootAssetId.split(':')[1], ois);
                rollUp(bom);
                createAssetsForBOM(bom);
            } else {
                bom = getBOMforAsset(rootAssetId);
                for (OrderItem oi : ois) {
                    if(getRootAssetId(oi) == rootAssetId) {
                        mergeOiToBOM(bom, oi);
                    }
                }
            }
            aggregate(bom);
        }
    }
    private Boolean isRootOrderItem(OrderItem oi) {
        return oi.Id == oi.SBQQ__BundleRoot__c;
    }
    private String getRootAssetId(OrderItem oi) {
        return oi.Modified_Root_Asset__c;
    }
    private NestedObject getBOMForOrderItem(Id rootOrderItemId, List<OrderItem> ois) {
        List<OrderItem> bomOis = new List<OrderItem>();
        for (OrderItem oi : ois) {
            if(oi.SBQQ__BundleRoot__c == rootOrderItemId) {
                bomOis.add(oi);
            }
        }
        return new NestedObject(
            bomOis,
            'Id',
            'SBQQ__RequiredBy__c'
        );
    }
    private void rollUp(NestedObject no) {

    }
    private void createAssetsForBOM(NestedObject bom) {
        for(NestedObject node : bom.all()) {
            node.relatedObjs.put('OrderItem', node.obj);
            node.replace(
                createAssetNode((OrderItem)node.obj)
            );
        }
    }
    private NestedObject getBOMForAsset(Id assetId, Datetime dt) {
        List<Asset> assets = PWUtils.selectStar(
            'Asset', 
            'RootAssetId = \'' + assetId + '\'',
            getAssetExpandFields()
        );
        return new NestedObject(
            assets,
            'Id',
            'ParentId'
        );
    }
    private void mergeOiToBOM(NestedObject bom, OrderItem oi) {
        if(oi.Asset__c != null) {
            // amendment to existing asset
            NestedObject match = bom.findById(oi.Asset__c);
            changeAsset(match, oi);
        } else {
            // new child of existing asset
            Id parentAssetId;
            if(oi.SBQQ__RequiredBy__c != null) {
                // Parent exists on the order
                parentAssetId = getOrderItemById(oi.SBQQ__RequiredBy__c).Asset__c;
            } else {
                // Parent not on the order
                parentAssetId = oi.SBQQ__QuoteLine__r.SBQQ__RequiredBy__r.SBQQ__UpgradedAsset__c;
            }
            NestedObject parentMatch = bom.findById(parentAssetId);
            parentMatch.addChild(
                createAssetNode(oi)
            );
        }
    }
    private NestedObject createAssetNode(OrderItem oi) {
        Asset a = new Asset(
            Name=oi.Product.Name,
            AccountId=oi.SBQQ__ShippingAccount__c
        );
        a.AssetStatePeriods.add(
            new AssetStatePeriod(
                StartDate=oi.ServiceDate,
                EndDate=oi.EndDate,
                Quantity=oi.Quantity,
                Mrr=mrr,
                Amount=oi.TotalPrice
            )
        );
        PWUtils.twinFields(oi, a, new String[]{'Name','AccountId'});
    }

}