force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Revision__c.field-meta.xml
<CustomField>
    <fullName>Quote_Revision__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quote Revision</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuoteExtController.cls
public with sharing class QuoteExtController {
	private Id quoteId;
	private SBQQ__Quote__c quote;
	
	public QuoteExtController(ApexPages.StandardController stdController) {
		quoteId = stdController.getId();      
		quote = (SBQQ__Quote__c)stdController.getRecord();
	}
	public PageReference onSubmit() {        
		if (quoteId != null) {
            try {
        		SBAA.ApprovalAPI.submit(quoteId, SBAA__Approval__c.Quote__c);            
            } catch (DMLException e) {                        		
        		displayMessage(e);
                return null;
            }
		}
		return new PageReference('/' + quoteId);
	}
	public PageReference onRecall() {
		if (quoteId != null) {
            try {
	            SBAA.ApprovalAPI.recall(quoteId, SBAA__Approval__c.Quote__c);			                
            } catch (DMLException e) {
                displayMessage(e);
                return null;
            }            
		}
        incrementQuoteRevision(quote);
		return new PageReference('/' + quoteId);
    }
    
    void displayMessage(Exception e){
        Apexpages.addmessage(new Apexpages.Message(ApexPages.Severity.Error,e.getDmlMessage(0)));                
    }
    
	@TestVisible private void incrementQuoteRevision(SBQQ__Quote__c quote) {
		if (quote.Quote_Revision__c != null) {
			quote.Quote_Revision__c++;
			upsert quote;
		}
	}
}