force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product quoted by this line item.</description>
    <inlineHelpText>Product quoted by this line item.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>R00N70000001lXB6EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemsTest.cls
@isTest
public class QuoteLineItemsTest {
    static Id quoteId='a00000000000000000';
    static QuoteLineItems ql = new QuoteLineItems();
    static List<SBQQ__QuoteLine__c> items = new List<SBQQ__QuoteLine__c>();

	@TestSetup
    static void makeData(){
        // Create test product
        Product2 testProd = new Product2(ProductCode='TESTPRD',Name='Test Product');
        insert testProd;
        
        // Create test quote
        SBQQ__Quote__c testQuote = new SBQQ__Quote__c(SBQQ__BillingCountry__c='Test Country');
        insert testQuote;
        
        // Add quote line to test quote        
		SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
            SBQQ__Quote__c = testQuote.Id,
            SBQQ__Product__c = testProd.Id
        );
        insert quoteLine;
    }
    
    @isTest
    static void TestGetSet() {        
        ql.quoteId = quoteId;
    	System.assertEquals('a00000000000000000', ql.quoteId);
    }
    
    @isTest
    static void TestQueryWithResult() {
		List<SBQQ__Quote__c> quotes = [SELECT Id FROM SBQQ__Quote__c WHERE SBQQ__BillingCountry__c='Test Country' LIMIT 1];
        for (SBQQ__Quote__c q:quotes){
        	ql.quoteId = q.Id;    
        }        
        items = ql.getLineItems();
        System.assert(items.size()>0);       
    }
    
    @isTest
    static void TestQueryWithoutResult() {
    	ql.quoteId = null;
        items = ql.getLineItems();
        System.assert(items.size() == 0);
    }    
}