force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ActionCalculateQuote.cls
public with sharing class ActionCalculateQuote implements Queueable, Database.AllowsCallouts {
    public Id quoteId;
    public ActionCalculateQuote(Id quoteId) {
        this.quoteId = quoteId;
    }
    public class InvocableParameter {
        @InvocableVariable(label='Quote Id')
        public Id quoteId;
    }
    @InvocableMethod(label='Calculate Quote')
    public static void calculateQuote(List<InvocableParameter> params) {
        for (InvocableParameter p : params) {
            // CPQ_QuoteCalculator.calculateAndSave(p.quoteId);
            // System.enqueueJob(new ActionCalculateQuote(p.quoteId));
            update [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :p.quoteId];
        }
    }
    public void execute(QueueableContext ctx) {
        update [SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :this.quoteId];
    }
}