force-app/main/default/objects/Product_Availability__c/Product_Availability__c.object-meta.xml
<CustomObject>
    <label>Product Availability</label>
    <nameField>
        <label>Product Availability Number</label>
        <type>AutoNumber</type>
        <displayFormat>PA-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Available Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Availability__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <label>Availability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value><fullName>New Sales</fullName><default>true</default><label>New Sales</label></value>
            <value><fullName>Amendments Only</fullName><default>false</default><label>Amendments Only</label></value>
            <value><fullName>Renewals Only</fullName><default>false</default><label>Renewals Only</label></value>
            <value><fullName>Not Available</fullName><default>false</default><label>Not Available</label></value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Availability__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Available Products</relationshipLabel>
    <relationshipName>Available_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Availability__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Available Products</relationshipLabel>
    <relationshipName>Available_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Availability__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Make</label>
    <referenceTo>Make__c</referenceTo>
    <relationshipLabel>Available Products</relationshipLabel>
    <relationshipName>Available_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Availability__c/fields/Manufacturer_Code__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Code__c</fullName>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Manufacturer_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Availability__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Availabilities</relationshipLabel>
    <relationshipName>Availabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CPQProductSearch.cls
global with sharing class CPQProductSearch implements SBQQ.ProductSearchPlugin {
    global Boolean isSearchCustom(SObject quote, Map<String,Object> fieldValuesMap) {
        return false;
    }
    global Boolean isFilterHidden(SObject quote, String fieldName) {
        return true;
    }
    global Boolean isInputHidden(SObject quote, String fieldName) {
        return true;
    }
    global Object getFilterDefaultValue(SObject quote, String fieldName) {
        return null;
    }
    global String getAdditionalSearchFilters(SObject quote, Map<String, Object> fieldValuesMap) {
        if(true){
            return null;
        }
        if(fieldValuesMap.keySet().size() > 0) {
            System.debug('FIELD VALUES MAP:\n' + JSON.serialize(fieldValuesMap));
        }
        SBQQ__Quote__c quoteObj = (SBQQ__Quote__c) quote;
        Account acct = [
            SELECT Id, Legal_Entity__c
            FROM Account
            WHERE Id = :quoteObj.SBQQ__Account__c
        ];
        String[] conditions = new String[]{};
        if(acct.Legal_Entity__c != null) {
            conditions.add('Legal_Entity__c = \'' + acct.Legal_Entity__c + '\'');
        }
        conditions.add('Customer__c = \'' + quoteObj.SBQQ__Account__c + '\''); // TODO handle hierarchies
        String[] mfgCodes = new String[]{};
        String[] makeIds = new String[]{};
        List<Account_Make_JO__c> accountMakes = [
            SELECT Id, Make__c, Manufacturer_Code__c
            FROM Account_Make_JO__c
            WHERE Account__c IN (
                SELECT Id
                FROM Account
                WHERE ParentId = :quoteObj.SBQQ__Account__c // TODO handle hierarchies
            )
        ];
        for (Account_Make_JO__c accountMake : accountMakes) {
            if(accountMake.Manufacturer_Code__c != null && !mfgCodes.contains(accountMake.Manufacturer_Code__c)) {
                mfgCodes.add(accountMake.Manufacturer_Code__c);
            }
            if(accountMake.Make__c != null && !makeIds.contains(accountMake.Make__c)) {
                makeIds.add(accountMake.Make__c);   
            }
        }
        if(mfgCodes.size() > 0) {
            conditions.add('Manufacturer_Code__c IN (\'' + String.join(mfgCodes, '\',\'') + '\')');
        }
        if(makeIds.size() > 0) {
            conditions.add('Make__c IN (\'' + String.join(makeIds, '\',\'') + '\')');
        }
        String conjunction = '';
        if(fieldValuesMap.keySet().size() > 0) {
            conjunction = ' AND ';
        }
        String additionalFilters = conjunction + 'Product2Id IN (SELECT Product__c FROM Product_Availability__c WHERE Availability__c != \'Not Available\' AND (' + String.join(conditions, ' OR ') + '))';
        System.debug('ADDITIONAL FILTERS:\n' + additionalFilters);
        return additionalFilters;
    }
    global List<PricebookEntry> search(SObject quote, Map<String,Object> fieldValuesMap){ 
        // Get all possible filter fields from the search filter field set
        List<Schema.FieldSetMember> searchFilterFieldSetFields = SObjectType.Product2.FieldSets.SBQQ__SearchFilters.getFields();
        // Get all possible fields from the search result field set
        List<Schema.FieldSetMember> searchResultFieldSetFields = SObjectType.Product2.FieldSets.SBQQ__SearchResults.getFields();
        // Build the Select string
        String selectClause = 'SELECT ';
        for(Schema.FieldSetMember field : searchResultFieldSetFields) {
            selectClause += 'Product2.' + field.getFieldPath() + ', ';
        }
        selectClause += 'Id, UnitPrice, Pricebook2Id, Product2Id, Product2.Id';
        // Build the Where clause
        String whereClause = '';
        for(Schema.FieldSetMember field : searchFilterFieldSetFields) {
            if(!fieldValuesMap.containsKey(field.getFieldPath())) {
            continue;
            }
            if(field.getType() == Schema.DisplayType.String || field.getType() == Schema.DisplayType.Picklist) {
            whereClause += 'Product2.' + field.getFieldPath() + ' LIKE \'%' + fieldValuesMap.get(field.getFieldPath()) + '%\' AND ';
            }
        }
        whereClause += 'Pricebook2Id = \'' + quote.get('SBQQ__Pricebook__c') + '\'';
        // Build the query
        String query = selectClause + ' FROM PricebookEntry WHERE ' + whereClause;
        // Perform the query
        List<PricebookEntry> pbes = new List<PricebookEntry>();
        pbes = Database.query(query);
        return pbes;
    }
    global Boolean isSuggestCustom(SObject quote, Map<String,Object> fieldValuesMap) {
        return false;
    }
    global String getAdditionalSuggestFilters(SObject quote, Map<String,Object> fieldValuesMap) {
        return null;
    }
    global List<PricebookEntry> suggest(SObject quote, Map<String,Object> fieldValuesMap) {
        return null;
    }
    global Object getInputDefaultValue(SObject quote, String fieldName) {
        return null;
    }

}